import { LinkType } from '../constant';
// 如需修改配置，请把ToolData和tools同步修改！！！
export const ToolData: Record<string, any> = {
  SigleImgText: {
    chineseName: '单图文',
    maxNum: 3,
    icon: 'singleImg',
    name: 'SigleImgText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: {
      src: 'a47b8070-f32a-4200-afe9-3a7d93c3e627.png',
      desc: '我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介',
      linkType: LinkType.BLANK,
      linkUrl: '',
    },
  },
  VerticalImageText: {
    chineseName: '竖图文',
    maxNum: 5,
    icon: 'verticalImgTxt',
    name: 'VerticalImageText',
    mainTitle: '主标题',
    bgColor: '#F5F6FB',
    configValue: [
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介',
        src: '4fb91eb4-c639-4bed-aea4-a355578760d7.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介',
        src: '4fb91eb4-c639-4bed-aea4-a355578760d7.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介',
        src: '4fb91eb4-c639-4bed-aea4-a355578760d7.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介',
        src: '4fb91eb4-c639-4bed-aea4-a355578760d7.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介',
        src: '4fb91eb4-c639-4bed-aea4-a355578760d7.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  ThreeImageText: {
    chineseName: '三图叠文',
    maxNum: 5,
    icon: 'threeImgTxt',
    name: 'ThreeImageText',
    mainTitle: '主标题',
    bgColor: '#F5F6FB',
    configValue: [
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介，我是简介，我是简介我是简介我是简介，我是简介我是简介我是简介我是简介。',
        src: '93d4af34-9f0a-4516-950c-6714bf2602f6.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介，我是简介，我是简介我是简介我是简介，我是简介我是简介我是简介我是简介。',
        src: '93d4af34-9f0a-4516-950c-6714bf2602f6.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介，我是简介，我是简介我是简介我是简介，我是简介我是简介我是简介我是简介。',
        src: '93d4af34-9f0a-4516-950c-6714bf2602f6.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  MultiImageText: {
    chineseName: '多图文',
    maxNum: 4,
    icon: 'multiImgTxt',
    name: 'MultiImageText',
    mainTitle: '主标题',
    bgColor: '#F5F6FB',
    configValue: [
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题',
        src: 'd291dde4-47df-462e-8564-85d291a29cd6.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题',
        src: 'eb3510ec-87b5-4d17-94a1-431439525a66.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题',
        src: 'db2dcf94-8aa5-4f4c-b1ee-5bfa24d30299.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题',
        src: '401b03a0-cd55-48fe-84d3-f461d58b61ea.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  IconImageText: {
    chineseName: '图标叠文',
    maxNum: 5,
    icon: 'iconTxt',
    name: 'IconImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: [
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: '12e87e00-67c9-448f-bad4-b6938da4d830.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: 'cfcd43ad-5be2-4ffa-a173-b2fc5061925c.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: 'e1f1abaf-2296-494c-9d7a-208b27668078.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: '35f3d0d8-e0a2-44a3-b4a0-f31cc3bda3b2.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  ImageOverlapText: {
    chineseName: '图叠文',
    maxNum: 3,
    icon: 'imgTxt',
    name: 'ImageOverlapText',
    mainTitle: '主标题',
    bgColor: '#ffffff#e2ecff',
    configValue: [
      {
        title: '小标题',
        src: '1a65b350-347e-4a40-8b83-5e5b45eb8fe8.png',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        src: 'fb8efc6e-70a2-4884-ab20-06614f030099.png',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        src: '78c60ec2-6332-4197-be3f-b0654257ff0c.png',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  LeftRightImageText: {
    chineseName: '左右图文',
    maxNum: 5,
    icon: 'leftRightImgTxt',
    name: 'LeftRightImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: [
      {
        title: '小标题',
        desc: '我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题。我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题',
        src: 'a34a8661-c656-42ef-92fb-d14cf97bf2dd.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题。我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题',
        src: 'a34a8661-c656-42ef-92fb-d14cf97bf2dd.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题我是副标题。我是副标题，我是副标题我是副标题，我是副标题我是副标题我是副标题我是副标题我是副标题',
        src: 'a34a8661-c656-42ef-92fb-d14cf97bf2dd.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  SpliceImageText: {
    chineseName: '拼图文',
    maxNum: 5,
    icon: 'stitchingImgTxt',
    name: 'SpliceImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue1: {
      subTitle: '我是主标题我是主标题',
      config: [
        {
          title: '小标题',
          desc: '我是简介我是简介我是简介我是简介我是简介',
          src: 'c18782ef-2879-4531-b946-f8d31c3ceded.png',
          linkType: LinkType.BLANK,
          linkUrl: '',
        },
        {
          title: '小标题',
          desc: '我是简介我是简介我是简介我是简介我是简介',
          src: 'c18782ef-2879-4531-b946-f8d31c3ceded.png',
          linkType: LinkType.BLANK,
          linkUrl: '',
        },
      ],
    },
    configValue2: {
      subTitle: '我是主标题我是主标题',
      config: [
        {
          title: '小标题',
          desc: '我是简介我是简介我是简介我是简介我是简介',
          src: 'c18782ef-2879-4531-b946-f8d31c3ceded.png',
          linkType: LinkType.BLANK,
          linkUrl: '',
        },
        {
          title: '小标题',
          desc: '我是简介我是简介我是简介我是简介我是简介',
          src: 'c18782ef-2879-4531-b946-f8d31c3ceded.png',
          linkType: LinkType.BLANK,
          linkUrl: '',
        },
      ],
    },
  },
  HerizontalImageText: {
    chineseName: '横图叠文',
    maxNum: 3,
    icon: 'imgTxt',
    name: 'HerizontalImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff#e2ecff',
    configValue: [
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: '2107b653-e08e-4f42-ae08-a89ecb649865.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: '265fb3ac-ee1d-4688-99db-09641ce81576.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是副标题我是副标题我是副标题我是副标题',
        src: '265fb3ac-ee1d-4688-99db-09641ce81576.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  CarouselImageText: {
    chineseName: '轮播图',
    maxNum: 5,
    icon: 'slideshow',
    name: 'CarouselImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: [
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介',
        src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介',
        src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '小标题',
        desc: '我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介我是简介',
        src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  MutiNavImageText: {
    chineseName: '多导航图文',
    maxNum: 8,
    icon: 'mutiNavImg',
    name: 'MutiNavImageText',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: [
      {
        title: '子导航',
        desc: '简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字',
        src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
      {
        title: '子导航',
        desc: '简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字简介二百字',
        src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
        linkType: LinkType.BLANK,
        linkUrl: '',
      },
    ],
  },
  SigleImg: {
    chineseName: '单图',
    maxNum: 1,
    icon: 'singleImg',
    name: 'SigleImg',
    mainTitle: '主标题',
    bgColor: '#ffffff',
    configValue: {
      src: 'f9075041-c2f9-4e7d-b75c-3afeee079129.png',
      desc: '',
      linkType: LinkType.BLANK,
      linkUrl: '',
    },
  },
};

export const tools = [
  'SigleImgText',
  'VerticalImageText',
  'ThreeImageText',
  'MultiImageText',
  'IconImageText',
  'ImageOverlapText',
  'LeftRightImageText',
  'SpliceImageText',
  'HerizontalImageText',
  'CarouselImageText',
  'MutiNavImageText',
  'SigleImg',
];
