import { LinkType } from '../constant';

export const ToolData: Record<string, any> = {
  SigleImg: {
    chineseName: '单图',
    maxNum: 3,
    icon: 'singleImg',
    name: 'SigleImg',
    mainTitle: '我是主标题',
    configValue: {
      title: '小标题',
      src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
      desc: '图片描述',
      linkType: LinkType.LINK,
      linkUrl: 'http://www.baidu.com',
    },
  },
  VerticalImageText: {
    chineseName: '竖图文',
    maxNum: 5,
    icon: 'verticalImgTxt',
    name: 'VerticalImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述',
        src: '2b3aaa8d-234d-44fc-b545-68413b3cd9ca.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述',
        src: '2b3aaa8d-234d-44fc-b545-68413b3cd9ca.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述',
        src: '2b3aaa8d-234d-44fc-b545-68413b3cd9ca.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述',
        src: '2b3aaa8d-234d-44fc-b545-68413b3cd9ca.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述',
        src: '2b3aaa8d-234d-44fc-b545-68413b3cd9ca.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  ThreeImageText: {
    chineseName: '三图叠文',
    maxNum: 5,
    icon: 'threeImgTxt',
    name: 'ThreeImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  MultiImageText: {
    chineseName: '多图文',
    maxNum: 4,
    icon: 'multiImgTxt',
    name: 'MultiImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  IconImageText: {
    chineseName: '图标叠文',
    maxNum: 5,
    icon: 'iconTxt',
    name: 'IconImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  ImageOverlapText: {
    chineseName: '图叠文',
    maxNum: 3,
    icon: 'imgTxt',
    name: 'ImageOverlapText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '区块1',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        desc: '图片描述图片描述',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '区块2',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        desc: '图片描述图片描述',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '区块3',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        desc: '图片描述图片描述',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  LeftRightImageText: {
    chineseName: '左右图文',
    maxNum: 5,
    icon: 'leftRightImgTxt',
    name: 'LeftRightImageText',
    mainTitle: '我是主标题66',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  SpliceImageText: {
    chineseName: '拼图文',
    maxNum: 5,
    icon: 'stitchingImgTxt',
    name: 'SpliceImageText',
    mainTitle: '我是主标题',
    configValue1: {
      subTitle: '左标题',
      config: [
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: 'bce9ffc8-92a7-4969-b465-8e07431b5841.JPG',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
      ],
    },
    configValue2: {
      subTitle: '右标题',
      config: [
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
        {
          title: '小标题',
          desc: '图片描述图片描述',
          src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
          linkType: LinkType.LINK,
          linkUrl: 'http://www.baidu.com',
        },
      ],
    },
  },
  HerizontalImageText: {
    chineseName: '横图叠文',
    maxNum: 3,
    icon: 'imgTxt',
    name: 'HerizontalImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: 'eb8a97de-c8a0-4d43-89e7-c39643070b3f.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
  CarouselImageText: {
    chineseName: '轮播图',
    maxNum: 5,
    icon: 'slideshow',
    name: 'CarouselImageText',
    mainTitle: '我是主标题',
    configValue: [
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
      {
        title: '小标题',
        desc: '图片描述图片描述',
        src: '909d785b-d3fa-4812-b117-557dfe8270e1.jpeg',
        linkType: LinkType.LINK,
        linkUrl: 'http://www.baidu.com',
      },
    ],
  },
};

export const tools = [
  'SigleImg',
  'VerticalImageText',
  'ThreeImageText',
  'MultiImageText',
  'IconImageText',
  'ImageOverlapText',
  'LeftRightImageText',
  'SpliceImageText',
  'HerizontalImageText',
  'CarouselImageText',
];
